In [1]:
import os
import json
import random
CORPUS_PATH = "leipzig-corpus"
TRAIN_FILE = "run-on-train.json"
TEST_FILE = "run-on-test.json"

def iter_islast(iterable):
    it = iter(iterable)
    prev = it.__next__()
    for item in it:
        yield prev, False
        prev = item
    yield (prev[:-1], prev[-1]), True

def extract_tokens_file(filename):
    tokens = []
    if filename.endswith("eng-eu_web_2015_10K-sentences.txt"):
        print("Processing: {}".format(filename))
        with open(filename, "r") as f:

            text = f.read().split("\n")
            res = []
            run_on_mode = False
            for line in text:
                if line:
                    line = line.split("\t")[1]
                    for token, is_last in iter_islast(line.split(" ")):
                        if is_last:
                            token1, token2 = token
                            #around 70% that it is run on
                            is_run_on = random.randint(1, 10) < 7
                            if is_run_on:
                                res.append([token1, True])
                                run_on_mode = True
                            else:
                                #this is the end of sentence
                                res.append([token1, False])
                                res.append([token2, False])
                                tokens.append(res)
                                res = []
                        else:
                            if run_on_mode:
                                if random.randint(0, 1): #this is 50% that run on is lower
                                    res.append([token.lower(), False])
                                    continue
                                run_on_mode = False
                            res.append([token, False])
    return tokens

with open(TRAIN_FILE, "w") as f:
    tokens = [extract_tokens_file("{}/{}".format(CORPUS_PATH, fl)) for fl in os.listdir(CORPUS_PATH)]
    tokens = [item for sublist in tokens for item in sublist]
    print("Extracted {} sentences".format(len(tokens)))
    print(tokens[:2])
    res = json.dumps(tokens, indent=4)
    f.write(res)

Processing: leipzig-corpus/eng-eu_web_2015_10K-sentences.txt
Extracted 3951 sentences
[[['01.08.2011', False], ['Public', False], ['call', False], ['for', False], ['standard', False], ['projects', False], ['No.', False], ['02/2009', False], ['.', False]], [['•', False], ['05.00', False], ['Energy', False], ['Rating', False], ['Introduce', False], ['energy', False], ['rating', False], ['models', False], ['for', False], ['selected', False], ['technologies', False], ['based', False], ['on', False], ['high', False], ['resolution', False], ['databases', False], ['in', False], ['the', False], ['Photovoltaic', False], ['Geographic', False], ['Information', False], ['System', False], ['(PVGIS),', False], ['also', False], ['in', False], ['collaboration', False], ['with', False], ['ENEA', True], ['06.00', False], ['Estimating', False], ['annual', False], ['farming', False], ['GHG', False], ['emissions', False], ['(including', False], ['Nitrous', False], ['Oxide', False], ['(N2O)', False], ['from

In [2]:
def word2features(sent, i):
    word = sent[i][0]
    label = sent[i][1]

    features = {
        'word.lower()': word.lower(),
#         'word[-3:]': word[-3:],
#         'word[-2:]': word[-2:],
        'word.isupper()': word.isupper(),
        'word.istitle()': word.istitle(),
        'word.isdigit()': word.isdigit(),
    }
    if i > 0:
        word1 = sent[i-1][0]
        features.update({
            '-1:word.lower()': word1.lower(),
            '-1:word.istitle()': word1.istitle(),
            '-1:word.isupper()': word1.isupper(),
        })
    else:
        features['BOS'] = True

    if i < len(sent)-1:
        word1 = sent[i+1][0]
        features.update({
            '+1:word.lower()': word1.lower(),
            '+1:word.istitle()': word1.istitle(),
            '+1:word.isupper()': word1.isupper(),
        })
    else:
        features['EOS'] = True

    return features, label

In [3]:
def get_tokens(f):
    features, labels = [], []
    with open(f, "r") as fl:
#         import ipdb; ipdb.set_trace()
        for sent in  json.loads(fl.read())[:3000]:
            for i in range(len(sent)):
                f, label = word2features(sent, i) 
                features.append(f)
                labels.append(label)
    return features, labels
train_features, train_labels = get_tokens(TRAIN_FILE)


In [4]:
train_features[:2]

[{'word.lower()': '01.08.2011',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'BOS': True,
  '+1:word.lower()': 'public',
  '+1:word.istitle()': True,
  '+1:word.isupper()': False},
 {'word.lower()': 'public',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  '-1:word.lower()': '01.08.2011',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '+1:word.lower()': 'call',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False}]

In [5]:
from collections import Counter
# print("test labels {}".format(Counter(test_labels)))
print("train labels {}".format(Counter(train_labels)))

train labels Counter({False: 153728, True: 4644})


In [6]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_features, train_labels, test_size=0.33)
vec = DictVectorizer()
x_train = vec.fit_transform(X_train).toarray()
print(x_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
from sklearn.linear_model import LogisticRegression
ls = LogisticRegression()
ls.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
# x_test = vec.transform(X_test).toarray()
# y_pred = ls.predict(x_test)

In [9]:
# from sklearn.metrics import classification_report
# print(classification_report(y_test, y_pred))
# 

In [12]:
from sklearn.metrics import classification_report
validation_features, validation_labels = get_tokens(TEST_FILE)
x_validation = vec.transform(validation_features).toarray()
validation_pred = ls.predict(x_validation)
print(classification_report(validation_labels, validation_pred))

             precision    recall  f1-score   support

      False       0.98      1.00      0.99      4542
       True       0.78      0.25      0.38       155

avg / total       0.97      0.97      0.97      4697



In [ ]:
# import numpy as np

# def top_features(vectorizer, clf, n):
#     """Prints features with the highest coefficient values, per class"""
#     feature_names = vectorizer.get_feature_names()
#     for i, class_label in enumerate(clf.classes_):
#         top = np.argsort(clf.coef_[i])
#         reversed_top = top[::-1]
#         print("%s: %s" % (class_label,
#               " ".join(feature_names[j] for j in reversed_top[:n])))
# top_features(vec, )